### ISSUE TITLE
Delete master branch

### ISSUE THREAD

**Issue by lcolladotor** [jtleek/protocols#6]
Hi,

The `master` branch is no longer needed, so it's best to delete it. Anyone who wants to see the files raw can do so on the gh-pages branch, for example https://github.com/jtleek/protocols/blob/gh-pages/tophat_cufflinks/index.Rmd. Or they can view the rendered version, for example http://jtleek.com/protocols/tophat_cufflinks/

To delete the `master` branch, first change the default branch to `gh-pages` on https://github.com/jtleek/protocols/settings

![screen shot 2014-10-03 at 4 39 40 pm](https://cloud.githubusercontent.com/assets/2288213/4512198/821723e8-4b3d-11e4-9fc0-22a08fa28d7e.png)

Then go to https://github.com/jtleek/protocols/branches and delete the `master` branch.

This will avoid any future confusion.

Cheers,
Leo

**Comment by lcolladotor** [comment]
I noticed you did this =) so I'm closing the issue.

**Comment by jtleek** [comment]
I do not want to delete the master for most of these because they are in use for classes, etc.

**Comment by lcolladotor** [comment]
The raw files are still accessible from the respective `gh-pages` branches. Just with a different name. Anyhow, I just think that having both branches will make it more confusing. And most likely harder to maintain with the same info.
