### ISSUE TITLE
Transfer to leekgroup

### ISSUE THREAD

**Issue by lcolladotor** [jtleek/protocols#7]
Jeff, I think that you can transfer this repo as well as many of your other repos to https://github.com/leekgroup

I believe that this won't mess up any of the forks people have made and the like (see [this](https://help.github.com/articles/transferring-a-repository/#redirects-and-git-remotes)). Although any docs with links like http://jtleek.com/protocols/ will have to change them to http://leekgroup.github.io/protocols/ Unless you:
- (a) also tranfser https://github.com/jtleek/jtleek.github.io to `leekgroup` and rename the repo `leekgroup.github.io`
- or (b) we add https://github.com/jtleek/jtleek.github.io/blob/master/CNAME to the repos under `leekgroup` that have a `gh-pages` branch.

Some refs:
- https://help.github.com/articles/transferring-a-repository/
- https://help.github.com/articles/user-organization-and-project-pages/
- https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/

List of other repos to transfer:
- https://github.com/jtleek/datasharing
- https://github.com/jtleek/careerplanning
- https://github.com/jtleek/genomicspapers
- https://github.com/jtleek/rpackages
- https://github.com/jtleek/reviews
- https://github.com/jtleek/datawomenontwitter
- https://github.com/jtleek/talkguide

**Comment by lcolladotor** [comment]
Regarding testing that transfering the repos to `leekgroup` doesn't break the urls at jtleek.com, here is how you can test it.

I made https://github.com/lcolladotor/testCNAME that has a `gh-pages` branch. Instead of transferring ownership I forked the repo to `leekgroup` at https://github.com/leekgroup/testCNAME which emulates transferring the repo. Next at `leekgroup/testCNAME` I added a CNAME file https://github.com/leekgroup/testCNAME/commit/13ecfa8798fe93c97ec24285379ca5d749e77368. For now, you can view the html at http://leekgroup.github.io/testCNAME/ but not at http://jtleek.com/testCNAME. In order for the file to be viewable at http://jtleek.com/testCNAME, according to https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/ you have to configure your DNS provider to redirect both jtleek.github.io and leekgroup.github.io to jtleek.com. Once you do that, http://jtleek.com/testCNAME should work.

**Comment by lcolladotor** [comment]
Although, really the easiest option would be to transfer https://github.com/jtleek/jtleek.github.io and rename the repo to be called `leekgroup.github.io`. Then because that repo would be the organization repo and has a CNAME file, everything would work. 

Note that if you transfer `jtleek/jtleek.github.io` you will also need to transfer the other repos you have under `jtleek` that have `gh-pages` branches if you want them to be viewable at http://jtleek.com

**Comment by lcolladotor** [comment]
Contacted support, and the only option would be to transfer `jtleek/jtleek.github.io` to `leekgroup` and rename it `leekgroup/leekgroup.github.io`. You'll probably also have to update your DNS.

Should be quite straight forward.

**Comment by jtleek** [comment]
I think I may just transfer the protocols repo but none of the other repos
